[build]
command = "cd react-app && npm install && npm run build"
publish = "react-app/dist"

[build.environment]
NODE_VERSION = "18"

[context.production]
command = "cd react-app && npm install && npm run build"
publish = "react-app/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
